// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHIHQ8BhOPySsTkQF34Yq_iihQZ-VJQGs',
    appId: '1:466515001217:android:42ce2fde89059d711e7280',
    messagingSenderId: '466515001217',
    projectId: 'streakly-tj-2026',
    databaseURL: 'https://streakly-tj-2026-default-rtdb.firebaseio.com',
    storageBucket: 'streakly-tj-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYEO03NHb1WGj7BKG8b2KiAEs_3GTgbZc',
    appId: '1:466515001217:web:35c43bdd223e41f51e7280',
    messagingSenderId: '466515001217',
    projectId: 'streakly-tj-2026',
    authDomain: 'streakly-tj-2026.firebaseapp.com',
    databaseURL: 'https://streakly-tj-2026-default-rtdb.firebaseio.com',
    storageBucket: 'streakly-tj-2026.firebasestorage.app',
  );
}
